logging:
  file:
    name: src/main/resources/eCommerce.log

spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: root
    driverClassName:
  mvc:
    pathMatch:
      matching-strategy: ant-path-matcher